//
// File generated by rootcint at Thu Feb 12 13:47:49 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BryceDirtCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BryceDirtCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      namespace larlite {

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::larlite::BryceDirtAna BryceDirtAna;
      #else
      class BryceDirtAna  :  public ::larlite::ana_base {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~BryceDirtAna() throw() {};
         double TPC_Xmin; //
         double TPC_Xmax; //
         double TPC_Ymin; //
         double TPC_Ymax; //
         double TPC_Zmin; //
         double TPC_Zmax; //
         ::TVector3 top_front_right; //
         ::TVector3 top_back_right; //
         ::TVector3 top_back_left; //
         ::TVector3 bottom_front_right; //
         ::TVector3 bottom_back_left; //
         ::TVector3 bottom_back_right; //
         ::TVector3 bottom_front_left; //
         double fid; //
         double fidz_min; //
         double fidz_max; //
         double fid_mu; //
         double fid_mu_z; //
         ::TVector3 ShowerStartPos; //
         ::TVector3 ShowerStartDir; //
         ::TVector3 TrackStartPos; //
         ::TVector3 TrackStartDir; //
         ::TTree* tree; //
         double shower_E; //
         int shower_pdg; //
         int shower_birth_ina; //
         int shower_birth_end_ina; //
         int shower_start_ina; //
         int shower_start_in_sliver; //
         int shower_convert_ina; //
         int shower_birth_pdg; //
         int shower_mom_pdg; //
         int shower_mom_start_ina; //
         int shower_vertex_Ntrk; //
         double shower_vertex_E; //
         double shower_vertex_L; //
         int shower_convert_inf_5cm_5cm_50cm; //
         int shower_convert_inf_30cm_5cm_50cm; //
         int shower_convert_inf_30cm_25cm_50cm; //
         int shower_convert_inf_30cm_20cm_50cm; //
         int shower_convert_inf_30cm_10cm_50cm; //
         int shower_convert_inf_30cm_15cm_50cm; //
         double shower_start_x; //
         double shower_start_y; //
         double shower_start_z; //
         int shower_extra_photons; //
         double shower_convert_x; //
         double shower_convert_y; //
         double shower_convert_z; //
         double shower_bdw; //
         int trk_start_ina; //
         int trk_pdg; //
         int trk_enter; //
         int trk_exit; //
         double nu_int_x; //
         double nu_int_y; //
         double nu_int_z; //
         int nu_pdg; //
         int nu_inf; //
         int nu_CC; //
         int nu_neutron; //
         int nu_neutron_ina; //
         int event; //
         int shower_multi_enter; //
      };
      #endif
      } 
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::sample sample;
      #else
      class sample  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~sample() throw() {};
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void larlitecLcLBryceDirtAna_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void larlitecLcLBryceDirtAna_Dictionary();
   static void *new_larlitecLcLBryceDirtAna(void *p = 0);
   static void *newArray_larlitecLcLBryceDirtAna(Long_t size, void *p);
   static void delete_larlitecLcLBryceDirtAna(void *p);
   static void deleteArray_larlitecLcLBryceDirtAna(void *p);
   static void destruct_larlitecLcLBryceDirtAna(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::larlite::BryceDirtAna*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::larlite::BryceDirtAna) == sizeof(::ROOT::Shadow::larlite::BryceDirtAna));
      ::larlite::BryceDirtAna *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::larlite::BryceDirtAna),0);
      static ::ROOT::TGenericClassInfo 
         instance("larlite::BryceDirtAna", "./BryceDirtAna.h", 27,
                  typeid(::larlite::BryceDirtAna), DefineBehavior(ptr, ptr),
                  &larlitecLcLBryceDirtAna_ShowMembers, &larlitecLcLBryceDirtAna_Dictionary, isa_proxy, 4,
                  sizeof(::larlite::BryceDirtAna) );
      instance.SetNew(&new_larlitecLcLBryceDirtAna);
      instance.SetNewArray(&newArray_larlitecLcLBryceDirtAna);
      instance.SetDelete(&delete_larlitecLcLBryceDirtAna);
      instance.SetDeleteArray(&deleteArray_larlitecLcLBryceDirtAna);
      instance.SetDestructor(&destruct_larlitecLcLBryceDirtAna);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::larlite::BryceDirtAna*)
   {
      return GenerateInitInstanceLocal((::larlite::BryceDirtAna*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::larlite::BryceDirtAna*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void larlitecLcLBryceDirtAna_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::larlite::BryceDirtAna*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void sample_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void sample_Dictionary();
   static void *new_sample(void *p = 0);
   static void *newArray_sample(Long_t size, void *p);
   static void delete_sample(void *p);
   static void deleteArray_sample(void *p);
   static void destruct_sample(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::sample*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::sample) == sizeof(::ROOT::Shadow::sample));
      ::sample *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::sample),0);
      static ::ROOT::TGenericClassInfo 
         instance("sample", "./sample.h", 24,
                  typeid(::sample), DefineBehavior(ptr, ptr),
                  &sample_ShowMembers, &sample_Dictionary, isa_proxy, 4,
                  sizeof(::sample) );
      instance.SetNew(&new_sample);
      instance.SetNewArray(&newArray_sample);
      instance.SetDelete(&delete_sample);
      instance.SetDeleteArray(&deleteArray_sample);
      instance.SetDestructor(&destruct_sample);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::sample*)
   {
      return GenerateInitInstanceLocal((::sample*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::sample*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void sample_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::sample*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void sample_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class sample.
      typedef ::ROOT::Shadow::sample ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::sample*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_sample(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::sample : new ::sample;
   }
   static void *newArray_sample(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::sample[nElements] : new ::sample[nElements];
   }
   // Wrapper around operator delete
   static void delete_sample(void *p) {
      delete ((::sample*)p);
   }
   static void deleteArray_sample(void *p) {
      delete [] ((::sample*)p);
   }
   static void destruct_sample(void *p) {
      typedef ::sample current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::sample

//______________________________________________________________________________
namespace ROOT {
   void larlitecLcLBryceDirtAna_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class larlite::BryceDirtAna.
      typedef ::ROOT::Shadow::larlite::BryceDirtAna ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::larlite::BryceDirtAna*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPC_Xmin", &sobj->TPC_Xmin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPC_Xmax", &sobj->TPC_Xmax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPC_Ymin", &sobj->TPC_Ymin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPC_Ymax", &sobj->TPC_Ymax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPC_Zmin", &sobj->TPC_Zmin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPC_Zmax", &sobj->TPC_Zmax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "top_front_right", &sobj->top_front_right);
      R__insp.InspectMember(sobj->top_front_right, "top_front_right.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "top_back_right", &sobj->top_back_right);
      R__insp.InspectMember(sobj->top_back_right, "top_back_right.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "top_back_left", &sobj->top_back_left);
      R__insp.InspectMember(sobj->top_back_left, "top_back_left.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bottom_front_right", &sobj->bottom_front_right);
      R__insp.InspectMember(sobj->bottom_front_right, "bottom_front_right.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bottom_back_left", &sobj->bottom_back_left);
      R__insp.InspectMember(sobj->bottom_back_left, "bottom_back_left.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bottom_back_right", &sobj->bottom_back_right);
      R__insp.InspectMember(sobj->bottom_back_right, "bottom_back_right.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bottom_front_left", &sobj->bottom_front_left);
      R__insp.InspectMember(sobj->bottom_front_left, "bottom_front_left.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fid", &sobj->fid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fidz_min", &sobj->fidz_min);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fidz_max", &sobj->fidz_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fid_mu", &sobj->fid_mu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fid_mu_z", &sobj->fid_mu_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ShowerStartPos", &sobj->ShowerStartPos);
      R__insp.InspectMember(sobj->ShowerStartPos, "ShowerStartPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ShowerStartDir", &sobj->ShowerStartDir);
      R__insp.InspectMember(sobj->ShowerStartDir, "ShowerStartDir.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrackStartPos", &sobj->TrackStartPos);
      R__insp.InspectMember(sobj->TrackStartPos, "TrackStartPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrackStartDir", &sobj->TrackStartDir);
      R__insp.InspectMember(sobj->TrackStartDir, "TrackStartDir.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tree", &sobj->tree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_E", &sobj->shower_E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_pdg", &sobj->shower_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_birth_ina", &sobj->shower_birth_ina);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_birth_end_ina", &sobj->shower_birth_end_ina);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_start_ina", &sobj->shower_start_ina);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_start_in_sliver", &sobj->shower_start_in_sliver);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_ina", &sobj->shower_convert_ina);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_birth_pdg", &sobj->shower_birth_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_mom_pdg", &sobj->shower_mom_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_mom_start_ina", &sobj->shower_mom_start_ina);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_vertex_Ntrk", &sobj->shower_vertex_Ntrk);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_vertex_E", &sobj->shower_vertex_E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_vertex_L", &sobj->shower_vertex_L);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_inf_5cm_5cm_50cm", &sobj->shower_convert_inf_5cm_5cm_50cm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_inf_30cm_5cm_50cm", &sobj->shower_convert_inf_30cm_5cm_50cm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_inf_30cm_25cm_50cm", &sobj->shower_convert_inf_30cm_25cm_50cm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_inf_30cm_20cm_50cm", &sobj->shower_convert_inf_30cm_20cm_50cm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_inf_30cm_10cm_50cm", &sobj->shower_convert_inf_30cm_10cm_50cm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_inf_30cm_15cm_50cm", &sobj->shower_convert_inf_30cm_15cm_50cm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_start_x", &sobj->shower_start_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_start_y", &sobj->shower_start_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_start_z", &sobj->shower_start_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_extra_photons", &sobj->shower_extra_photons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_x", &sobj->shower_convert_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_y", &sobj->shower_convert_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_convert_z", &sobj->shower_convert_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_bdw", &sobj->shower_bdw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trk_start_ina", &sobj->trk_start_ina);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trk_pdg", &sobj->trk_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trk_enter", &sobj->trk_enter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trk_exit", &sobj->trk_exit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_int_x", &sobj->nu_int_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_int_y", &sobj->nu_int_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_int_z", &sobj->nu_int_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_pdg", &sobj->nu_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_inf", &sobj->nu_inf);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_CC", &sobj->nu_CC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_neutron", &sobj->nu_neutron);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nu_neutron_ina", &sobj->nu_neutron_ina);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "event", &sobj->event);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "shower_multi_enter", &sobj->shower_multi_enter);
      R__insp.GenericShowMembers("larlite::ana_base", ( ::larlite::ana_base * )( (::larlite::BryceDirtAna*) obj ), false);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_larlitecLcLBryceDirtAna(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::larlite::BryceDirtAna : new ::larlite::BryceDirtAna;
   }
   static void *newArray_larlitecLcLBryceDirtAna(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::larlite::BryceDirtAna[nElements] : new ::larlite::BryceDirtAna[nElements];
   }
   // Wrapper around operator delete
   static void delete_larlitecLcLBryceDirtAna(void *p) {
      delete ((::larlite::BryceDirtAna*)p);
   }
   static void deleteArray_larlitecLcLBryceDirtAna(void *p) {
      delete [] ((::larlite::BryceDirtAna*)p);
   }
   static void destruct_larlitecLcLBryceDirtAna(void *p) {
      typedef ::larlite::BryceDirtAna current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::larlite::BryceDirtAna

/********************************************************
* BryceDirtCint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBryceDirtCint();

extern "C" void G__set_cpp_environmentBryceDirtCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BryceDirtAna.h");
  G__add_compiledheader("sample.h");
  G__cpp_reset_tagtableBryceDirtCint();
}
#include <new>
extern "C" int G__cpp_dllrevBryceDirtCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* larlite::BryceDirtAna */
static int G__BryceDirtCint_710_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   larlite::BryceDirtAna* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new larlite::BryceDirtAna[n];
     } else {
       p = new((void*) gvp) larlite::BryceDirtAna[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new larlite::BryceDirtAna;
     } else {
       p = new((void*) gvp) larlite::BryceDirtAna;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BryceDirtCint_710_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((larlite::BryceDirtAna*) G__getstructoffset())->ctr_reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BryceDirtCint_710_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((larlite::BryceDirtAna*) G__getstructoffset())->IsActive(*(TVector3*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BryceDirtCint_710_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((larlite::BryceDirtAna*) G__getstructoffset())->IsFiducial(*(TVector3*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BryceDirtCint_710_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((larlite::BryceDirtAna*) G__getstructoffset())->IntersectsPlane(*(TVector3*) libp->para[0].ref, *(TVector3*) libp->para[1].ref
, *(TVector3*) libp->para[2].ref, *(TVector3*) libp->para[3].ref
, *(TVector3*) libp->para[4].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BryceDirtCint_710_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   larlite::BryceDirtAna* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new larlite::BryceDirtAna(*(larlite::BryceDirtAna*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef larlite::BryceDirtAna G__TlarlitecLcLBryceDirtAna;
static int G__BryceDirtCint_710_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (larlite::BryceDirtAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((larlite::BryceDirtAna*) (soff+(sizeof(larlite::BryceDirtAna)*i)))->~G__TlarlitecLcLBryceDirtAna();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (larlite::BryceDirtAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((larlite::BryceDirtAna*) (soff))->~G__TlarlitecLcLBryceDirtAna();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BryceDirtCint_710_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   larlite::BryceDirtAna* dest = (larlite::BryceDirtAna*) G__getstructoffset();
   *dest = *(larlite::BryceDirtAna*) libp->para[0].ref;
   const larlite::BryceDirtAna& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* sample */
static int G__BryceDirtCint_711_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   sample* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new sample[n];
     } else {
       p = new((void*) gvp) sample[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new sample;
     } else {
       p = new((void*) gvp) sample;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BryceDirtCintLN_sample));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BryceDirtCint_711_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sample*) G__getstructoffset())->HelloWorld();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BryceDirtCint_711_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   sample* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new sample(*(sample*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BryceDirtCintLN_sample));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef sample G__Tsample;
static int G__BryceDirtCint_711_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (sample*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((sample*) (soff+(sizeof(sample)*i)))->~G__Tsample();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (sample*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((sample*) (soff))->~G__Tsample();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BryceDirtCint_711_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   sample* dest = (sample*) G__getstructoffset();
   *dest = *(sample*) libp->para[0].ref;
   const sample& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* larlite::BryceDirtAna */

/* sample */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBryceDirtCint {
 public:
  G__Sizep2memfuncBryceDirtCint(): p(&G__Sizep2memfuncBryceDirtCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBryceDirtCint::*p)();
};

size_t G__get_sizep2memfuncBryceDirtCint()
{
  G__Sizep2memfuncBryceDirtCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBryceDirtCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna))) {
     larlite::BryceDirtAna *G__Lderived;
     G__Lderived=(larlite::BryceDirtAna*)0x1000;
     {
       larlite::ana_base *G__Lpbase=(larlite::ana_base*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna),G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLana_base),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       larlite::larlite_base *G__Lpbase=(larlite::larlite_base*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna),G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLlarlite_base),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBryceDirtCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AssUnit_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<unsigned int,allocator<unsigned int> > >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<larlite::data::DataType_t,std::string>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_pairlElarlitecLcLdatacLcLDataType_tcOstringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<product_id,AssSet_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplElarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcOlesslElarlitecLcLproduct_idgRcOallocatorlEpairlEconstsPlarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<larlite::product_id,vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > > >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplElarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcOlesslElarlitecLcLproduct_idgRcOallocatorlEpairlEconstsPlarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<larlite::product_id,vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >,less<larlite::product_id> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplElarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcOlesslElarlitecLcLproduct_idgRcOallocatorlEpairlEconstsPlarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlite::product_id>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,larlite::event_base*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,larlite::event_base*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,larlite::event_base*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,larlite::event_base*,less<string> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::map<std::string,larlite::event_base*> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,larlite::event_base*> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,larlite::event_base*,less<string>,allocator<pair<const string,larlite::event_base*> > > >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TChain*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TChain*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TChain*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TChain*,less<string> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::map<std::string,TChain*> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,TChain*> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,TChain*,less<string>,allocator<pair<const string,TChain*> > > >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TTree*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TTree*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TTree*>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TTree*,less<string> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::map<std::string,TTree*> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,TTree*> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,TTree*,less<string>,allocator<pair<const string,TTree*> > > >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,bool>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::map<std::string,bool> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,bool> >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<string,bool,less<string>,allocator<pair<const string,bool> > > >",117,G__get_linked_tagnum(&G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__BryceDirtCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* larlite::BryceDirtAna */
static void G__setup_memvarlarlitecLcLBryceDirtAna(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna));
   { larlite::BryceDirtAna *p; p=(larlite::BryceDirtAna*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"TPC_Xmin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"TPC_Xmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"TPC_Ymin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"TPC_Ymax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"TPC_Zmin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"TPC_Zmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"top_front_right=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"top_back_right=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"top_back_left=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"bottom_front_right=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"bottom_back_left=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"bottom_back_right=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"bottom_front_left=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fid=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fidz_min=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fidz_max=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fid_mu=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fid_mu_z=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"ShowerStartPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"ShowerStartDir=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"TrackStartPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TVector3),-1,-1,2,"TrackStartDir=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BryceDirtCintLN_TTree),-1,-1,2,"tree=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_E=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_birth_ina=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_birth_end_ina=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_start_ina=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_start_in_sliver=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_convert_ina=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_birth_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_mom_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_mom_start_ina=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_vertex_Ntrk=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_vertex_E=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_vertex_L=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_convert_inf_5cm_5cm_50cm=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_convert_inf_30cm_5cm_50cm=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_convert_inf_30cm_25cm_50cm=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_convert_inf_30cm_20cm_50cm=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_convert_inf_30cm_10cm_50cm=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_convert_inf_30cm_15cm_50cm=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_start_x=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_start_y=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_start_z=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_extra_photons=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_convert_x=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_convert_y=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_convert_z=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"shower_bdw=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"trk_start_ina=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"trk_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"trk_enter=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"trk_exit=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"nu_int_x=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"nu_int_y=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"nu_int_z=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nu_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nu_inf=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nu_CC=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nu_neutron=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nu_neutron_ina=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"event=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"shower_multi_enter=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* sample */
static void G__setup_memvarsample(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BryceDirtCintLN_sample));
   { sample *p; p=(sample*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBryceDirtCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfunclarlitecLcLBryceDirtAna(void) {
   /* larlite::BryceDirtAna */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna));
   G__memfunc_setup("BryceDirtAna",1176,G__BryceDirtCint_710_0_1, 105, G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("initialize",1074,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("analyze",756,(G__InterfaceMethod) NULL,103, -1, -1, 0, 1, 1, 1, 0, "U 'larlite::storage_manager' - 0 - storage", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("finalize",850,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ctr_reset",971,G__BryceDirtCint_710_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsActive",792,G__BryceDirtCint_710_0_6, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TVector3' - 11 - startPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsFiducial",989,G__BryceDirtCint_710_0_7, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TVector3' - 11 - startPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IntersectsPlane",1556,G__BryceDirtCint_710_0_8, 105, -1, -1, 0, 5, 1, 1, 0, 
"u 'TVector3' - 11 - startPos u 'TVector3' - 11 - startDir "
"u 'TVector3' - 11 - planeCorner1 u 'TVector3' - 11 - planeCorner2 "
"u 'TVector3' - 11 - planeCorner3", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BryceDirtAna", 1176, G__BryceDirtCint_710_0_9, (int) ('i'), G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna), -1, 0, 1, 1, 1, 0, "u 'larlite::BryceDirtAna' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BryceDirtAna", 1302, G__BryceDirtCint_710_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BryceDirtCint_710_0_11, (int) ('u'), G__get_linked_tagnum(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna), -1, 1, 1, 1, 1, 0, "u 'larlite::BryceDirtAna' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncsample(void) {
   /* sample */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BryceDirtCintLN_sample));
   G__memfunc_setup("sample",642,G__BryceDirtCint_711_0_1, 105, G__get_linked_tagnum(&G__BryceDirtCintLN_sample), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HelloWorld",1020,G__BryceDirtCint_711_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("sample", 642, G__BryceDirtCint_711_0_3, (int) ('i'), G__get_linked_tagnum(&G__BryceDirtCintLN_sample), -1, 0, 1, 1, 1, 0, "u 'sample' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~sample", 768, G__BryceDirtCint_711_0_4, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BryceDirtCint_711_0_5, (int) ('u'), G__get_linked_tagnum(&G__BryceDirtCintLN_sample), -1, 1, 1, 1, 1, 0, "u 'sample' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBryceDirtCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBryceDirtCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBryceDirtCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BryceDirtCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_larlite = { "larlite" , 110 , -1 };
G__linked_taginfo G__BryceDirtCintLN_larlitecLcLlarlite_base = { "larlite::larlite_base" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR = { "vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_pairlElarlitecLcLdatacLcLDataType_tcOstringgR = { "pair<larlite::data::DataType_t,string>" , 115 , -1 };
G__linked_taginfo G__BryceDirtCintLN_maplElarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcOlesslElarlitecLcLproduct_idgRcOallocatorlEpairlEconstsPlarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRsPgRsPgRsPgR = { "map<larlite::product_id,vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >,less<larlite::product_id>,allocator<pair<const larlite::product_id,vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > > > > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgR = { "vector<larlite::product_id,allocator<larlite::product_id> >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlite::product_id,allocator<larlite::product_id> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_larlitecLcLstorage_manager = { "larlite::storage_manager" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_maplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgR = { "map<string,larlite::event_base*,less<string>,allocator<pair<const string,larlite::event_base*> > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR = { "vector<map<string,larlite::event_base*,less<string>,allocator<pair<const string,larlite::event_base*> > >,allocator<map<string,larlite::event_base*,less<string>,allocator<pair<const string,larlite::event_base*> > > > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<string,larlite::event_base*,less<string>,allocator<pair<const string,larlite::event_base*> > >,allocator<map<string,larlite::event_base*,less<string>,allocator<pair<const string,larlite::event_base*> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR = { "map<string,TChain*,less<string>,allocator<pair<const string,TChain*> > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR = { "vector<map<string,TChain*,less<string>,allocator<pair<const string,TChain*> > >,allocator<map<string,TChain*,less<string>,allocator<pair<const string,TChain*> > > > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<string,TChain*,less<string>,allocator<pair<const string,TChain*> > >,allocator<map<string,TChain*,less<string>,allocator<pair<const string,TChain*> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR = { "map<string,TTree*,less<string>,allocator<pair<const string,TTree*> > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR = { "vector<map<string,TTree*,less<string>,allocator<pair<const string,TTree*> > >,allocator<map<string,TTree*,less<string>,allocator<pair<const string,TTree*> > > > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<string,TTree*,less<string>,allocator<pair<const string,TTree*> > >,allocator<map<string,TTree*,less<string>,allocator<pair<const string,TTree*> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR = { "vector<map<string,bool,less<string>,allocator<pair<const string,bool> > >,allocator<map<string,bool,less<string>,allocator<pair<const string,bool> > > > >" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<string,bool,less<string>,allocator<pair<const string,bool> > >,allocator<map<string,bool,less<string>,allocator<pair<const string,bool> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_larlitecLcLana_base = { "larlite::ana_base" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_larlitecLcLBryceDirtAna = { "larlite::BryceDirtAna" , 99 , -1 };
G__linked_taginfo G__BryceDirtCintLN_sample = { "sample" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBryceDirtCint() {
  G__BryceDirtCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_larlite.tagnum = -1 ;
  G__BryceDirtCintLN_larlitecLcLlarlite_base.tagnum = -1 ;
  G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__BryceDirtCintLN_TTree.tagnum = -1 ;
  G__BryceDirtCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_pairlElarlitecLcLdatacLcLDataType_tcOstringgR.tagnum = -1 ;
  G__BryceDirtCintLN_maplElarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcOlesslElarlitecLcLproduct_idgRcOallocatorlEpairlEconstsPlarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_larlitecLcLstorage_manager.tagnum = -1 ;
  G__BryceDirtCintLN_maplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BryceDirtCintLN_larlitecLcLana_base.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__BryceDirtCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BryceDirtCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__BryceDirtCintLN_TVector3.tagnum = -1 ;
  G__BryceDirtCintLN_larlitecLcLBryceDirtAna.tagnum = -1 ;
  G__BryceDirtCintLN_sample.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBryceDirtCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_larlite);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_larlitecLcLlarlite_base);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TTree);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_pairlElarlitecLcLdatacLcLDataType_tcOstringgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_maplElarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcOlesslElarlitecLcLproduct_idgRcOallocatorlEpairlEconstsPlarlitecLcLproduct_idcOvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlElarlitecLcLproduct_idcOallocatorlElarlitecLcLproduct_idgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_larlitecLcLstorage_manager);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_maplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRcOallocatorlEmaplEstringcOlarlitecLcLevent_basemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOlarlitecLcLevent_basemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_maplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRcOallocatorlEmaplEstringcOTChainmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChainmUgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRcOallocatorlEmaplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_vectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_reverse_iteratorlEvectorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcOallocatorlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_larlitecLcLana_base);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_larlitecLcLBryceDirtAna),sizeof(larlite::BryceDirtAna),-1,263424,(char*)NULL,G__setup_memvarlarlitecLcLBryceDirtAna,G__setup_memfunclarlitecLcLBryceDirtAna);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BryceDirtCintLN_sample),sizeof(sample),-1,263424,(char*)NULL,G__setup_memvarsample,G__setup_memfuncsample);
}
extern "C" void G__cpp_setupBryceDirtCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupBryceDirtCint()");
  G__set_cpp_environmentBryceDirtCint();
  G__cpp_setup_tagtableBryceDirtCint();

  G__cpp_setup_inheritanceBryceDirtCint();

  G__cpp_setup_typetableBryceDirtCint();

  G__cpp_setup_memvarBryceDirtCint();

  G__cpp_setup_memfuncBryceDirtCint();
  G__cpp_setup_globalBryceDirtCint();
  G__cpp_setup_funcBryceDirtCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBryceDirtCint();
  return;
}
class G__cpp_setup_initBryceDirtCint {
  public:
    G__cpp_setup_initBryceDirtCint() { G__add_setup_func("BryceDirtCint",(G__incsetup)(&G__cpp_setupBryceDirtCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBryceDirtCint() { G__remove_setup_func("BryceDirtCint"); }
};
G__cpp_setup_initBryceDirtCint G__cpp_setup_initializerBryceDirtCint;

